services:
  postgres:
    image: postgres:13
    container_name: hive-postgres
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hive-net

  metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    depends_on:
      - postgres
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password"
    ports:
      - "9083:9083"
    volumes:
      - ./data:/data       
    networks:
      - hive-net
    command: >
      /bin/bash -c "
        echo 'Waiting for Postgres...' && sleep 5;
        /opt/hive/bin/schematool -dbType postgres -initSchema -driver org.postgresql.Driver -userName hive -passWord password -url jdbc:postgresql://postgres:5432/metastore_db || true;
        echo 'Starting Metastore...' &&
        /opt/hive/bin/hive --service metastore"

  hiveserver2:
    image: apache/hive:3.1.3
    container_name: hive-server
    depends_on:
      - metastore
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083"
      SKIP_SCHEMA_INIT: "true" #this is ignored for some reason :(
    ports:
      - "10000:10000"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      #- ./hive-site.xml:/opt/hive/conf/hive-site.xml #hook setup https://docs.cloud.google.com/bigquery/docs/migration-assessment#configure-properties
      #- ./tez-site.xml:/opt/hive/conf/tez-site.xml #setup to avoit rate limiting
      - ./hive-hook/HiveMigrationAssessmentQueryLogsHooks_deploy.jar:/opt/hive-hook/HiveMigrationAssessmentQueryLogsHooks_deploy.jar #hook from https://github.com/google/hadoop-migration-assessment-tools/releases/tag/v1.0.2
    user: "root"
    networks:
      - hive-net

networks:
  hive-net: #needs to setup a netowork without underscore "_" character, otherwise beeline crashes ;e
    name: hivenet

volumes:
  pgdata: